export async function listingsRetrivalError(catchError) {
  console.log('OPS! Error with retriving listings', catchError);
}
