export async function loginError(catchError) {
  console.log('OPS! Error with registration', catchError);
}
